ALTER TABLE sites ADD COLUMN appartment_name VARCHAR(150);
ALTER TABLE sites ADD COLUMN floor_no VARCHAR(50);
ALTER TABLE sites ADD COLUMN city VARCHAR(100);
ALTER TABLE sites ADD COLUMN state VARCHAR(100);
ALTER TABLE sites ADD COLUMN country VARCHAR(100);
ALTER TABLE sites ADD COLUMN zip_code BIGINT;